'use strict';
/* ═══════════════════════════════════════════════════
   EXCEL.JS — Professional Workpaper Export
   Uses SheetJS (xlsx) to build multi-sheet Excel
   with proper formatting, formulas & styles
═══════════════════════════════════════════════════ */
const Excel = (() => {

  const FIRM   = 'K G Somani & Co LLP';
  const TOOL   = 'Income Tax Provision Workpaper — Ind AS 12';

  /* ── grab current computed result ── */
  function getResult(){
    const r = Compute.run(State.data);
    return r;
  }

  /* ── helpers ── */
  const v  = id => parseFloat(document.getElementById(id)?.value)||0;
  const s  = id => document.getElementById(id)?.value||'';
  const fmt= n  => Math.round(n)||0;

  /* ══════════════════════════════════════
     MASTER EXPORT FUNCTION
  ══════════════════════════════════════ */
  async function exportWorkpaper(){
    UI.toast('Generating Excel workpaper…','info',3000);

    /* Load SheetJS from CDN */
    if(!window.XLSX){
      try{
        await loadScript('https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js');
      } catch(e){
        UI.toast('Could not load Excel library. Check internet connection.','err');
        return;
      }
    }

    const result = getResult();
    if(!result){ UI.toast('Please compute first.','err'); return; }
    const { ct, dt, total, etr } = result;

    const WB = XLSX.utils.book_new();
    WB.Props = { Title: TOOL, Author: FIRM, CreatedDate: new Date() };

    /* ── SHEET 1: Cover / Index ── */
    addCoverSheet(WB, ct, dt, total, etr);

    /* ── SHEET 2: Current Tax ── */
    addCurrentTaxSheet(WB, ct);

    /* ── SHEET 3: Deferred Tax Schedule ── */
    addDeferredTaxSheet(WB, dt);

    /* ── SHEET 4: DTA-DTL Movement ── */
    addMovementSheet(WB, dt);

    /* ── SHEET 5: Journal Entries ── */
    addJESheet(WB, ct, dt);

    /* ── SHEET 6: Disclosure Note ── */
    addDisclosureSheet(WB, ct, dt, total, etr);

    /* ── SHEET 7: ETR Reconciliation ── */
    addETRSheet(WB, ct, dt, total, etr);

    /* ── SHEET 8: Auditor Checklist ── */
    addChecklistSheet(WB);

    /* Download */
    const client = s('ci-name').replace(/\s+/g,'_')||'Client';
    const fy     = s('ci-fy').replace(/[^0-9-]/g,'')||'FY';
    const fname  = `KGS_TaxProvision_${client}_${fy}.xlsx`;
    XLSX.writeFile(WB, fname);
    UI.toast('Excel workpaper downloaded ✓','ok');
  }

  /* ══════════════════════════════════════
     SHEET 1 — COVER
  ══════════════════════════════════════ */
  function addCoverSheet(WB, ct, dt, total, etr){
    const rate = v('ci-rate');
    const rows = [
      ['','','','',''],
      [FIRM,'','','',''],
      ['Chartered Accountants','','','',''],
      ['','','','',''],
      [TOOL,'','','',''],
      ['','','','',''],
      ['CLIENT DETAILS','','','',''],
      ['Client Name',s('ci-name'),'','',''],
      ['CIN / PAN',s('ci-cin'),'','',''],
      ['Financial Year',s('ci-fy'),'','',''],
      ['Balance Sheet Date',s('ci-date'),'','',''],
      ['Tax Regime',s('ci-regime'),'','',''],
      ['Applicable Tax Rate',rate.toFixed(3)+'%','','',''],
      ['MAT Rate',v('ci-mat').toFixed(3)+'%','','',''],
      ['','','','',''],
      ['ENGAGEMENT','','','',''],
      ['Prepared By',s('ci-prep'),'','',''],
      ['Reviewed By',s('ci-rev'),'','',''],
      ['Date of Preparation',s('ci-prepdate'),'','',''],
      ['','','','',''],
      ['SUMMARY OF PROVISION','','AMOUNT (₹)','',''],
      ['Current Tax (Gross)',''  ,fmt(ct.grossTax),'',''],
      ['Deferred Tax Charge / (Credit)','',fmt(dt.dtPLCharge),'',''],
      ['Total Income Tax Expense','',fmt(total),'',''],
      ['Net Current Tax Payable','',fmt(ct.netCT),'',''],
      ['Closing DTA (Balance Sheet)','',fmt(dt.closingDTA),'',''],
      ['Closing DTL (Balance Sheet)','',fmt(dt.closingDTL),'',''],
      ['Effective Tax Rate','',etr.toFixed(2)+'%','',''],
      ['Statutory Tax Rate','',rate.toFixed(3)+'%','',''],
      ['','','','',''],
      ['WORKPAPER INDEX','','SHEET','',''],
      ['Current Tax Computation','','CT','',''],
      ['Deferred Tax Schedule (Ind AS 12)','','DT','',''],
      ['DTA / DTL Movement Schedule','','MOV','',''],
      ['Journal Entries','','JE','',''],
      ['Ind AS 12 Disclosure Note','','DISC','',''],
      ['ETR Reconciliation','','ETR','',''],
      ['Auditor Checklist','','CHK','',''],
      ['','','','',''],
      ['Generated by: KGS Tax Provision Tool | '+new Date().toLocaleDateString('en-IN'),'','','',''],
    ];

    const WS = XLSX.utils.aoa_to_sheet(rows);
    WS['!cols'] = [{wch:46},{wch:32},{wch:20},{wch:12},{wch:12}];
    WS['!merges']=[
      {s:{r:1,c:0},e:{r:1,c:4}},{s:{r:2,c:0},e:{r:2,c:4}},
      {s:{r:4,c:0},e:{r:4,c:4}},{s:{r:38,c:0},e:{r:38,c:4}},
    ];
    XLSX.utils.book_append_sheet(WB, WS, 'COVER');
  }

  /* ══════════════════════════════════════
     SHEET 2 — CURRENT TAX
  ══════════════════════════════════════ */
  function addCurrentTaxSheet(WB, ct){
    const rate = v('ci-rate');
    const rows = [
      [FIRM],
      ['CURRENT TAX COMPUTATION — Income Tax Act, 1961'],
      ['Client: '+s('ci-name')+'  |  FY: '+s('ci-fy')+'  |  Rate: '+rate.toFixed(3)+'%'],
      [''],
      ['SR','TYPE','PARTICULARS','AMOUNT (₹)','NOTES'],
    ];

    let taxable = 0;
    let bookProfit = 0;
    State.data.ctRows.forEach((r,i)=>{
      const amt = parseFloat(r.amt)||0;
      if(r.type==='book') bookProfit = amt;
      const sign = r.type==='less' ? -amt : amt;
      if(r.type==='book') taxable = amt;
      else if(r.type==='add') taxable += amt;
      else taxable -= amt;
      rows.push([i+1, r.type.toUpperCase(), r.label, amt, '']);
    });

    rows.push(['','','','','']);
    rows.push(['','','TAXABLE INCOME / (LOSS)',taxable,'']);
    rows.push(['','','','','']);
    rows.push(['','','','','']);
    rows.push(['','','TAX COMPUTATION','','']);
    rows.push(['','','Taxable Income',taxable,'']);
    rows.push(['','','Tax Rate',rate.toFixed(3)+'%','']);
    rows.push(['','','Gross Tax Liability',fmt(ct.grossTax),'=C'+(rows.length+1)+'*'+rate/100]);
    rows.push(['','','Less: MAT Credit Utilised',fmt(ct.matUtil),'']);
    rows.push(['','','Less: Advance Tax / TDS',fmt(ct.tds),'']);
    rows.push(['','','NET CURRENT TAX PAYABLE',fmt(ct.netCT),'']);

    const WS = XLSX.utils.aoa_to_sheet(rows);
    WS['!cols']=[{wch:6},{wch:8},{wch:56},{wch:20},{wch:32}];
    XLSX.utils.book_append_sheet(WB, WS, 'CT');
  }

  /* ══════════════════════════════════════
     SHEET 3 — DEFERRED TAX
  ══════════════════════════════════════ */
  function addDeferredTaxSheet(WB, dt){
    const rate = v('ci-rate');
    const rows = [
      [FIRM],
      ['DEFERRED TAX SCHEDULE — Ind AS 12 (Balance Sheet Approach)'],
      ['Client: '+s('ci-name')+'  |  FY: '+s('ci-fy')+'  |  Tax Rate: '+rate.toFixed(3)+'%'],
      ['Note: Temp Diff = Carrying Amount (Ind AS) − Tax Base (Income Tax Act, 1961)'],
      [''],
      ['SECTION A — ASSETS'],
      ['For Assets: CA > Tax Base → Taxable Temp. Difference → DTL  |  CA < Tax Base → Deductible Temp. Difference → DTA'],
      ['SR','PARTICULARS','CARRYING AMT (₹)','TAX BASE (₹)','TEMP DIFF (₹)','NATURE','TAX EFFECT (₹)','NOTES'],
    ];

    let aTotalDTA=0, aTotalDTL=0;
    dt.assetRows.forEach((r,i)=>{
      rows.push([i+1,r.label,fmt(r.ca),fmt(r.tb),fmt(r.diff),r.nature,fmt(r.te),r.note||'']);
      if(r.nature==='DTA') aTotalDTA+=r.te; else if(r.nature==='DTL') aTotalDTL+=r.te;
    });
    rows.push(['','SUBTOTAL — ASSETS','','','','DTA',fmt(aTotalDTA),'']);
    rows.push(['','','','','','DTL',fmt(aTotalDTL),'']);

    rows.push([''],
    ['SECTION B — LIABILITIES & PROVISIONS'],
    ['For Liabilities: CA > Tax Base → Deductible Temp. Difference → DTA  |  CA < Tax Base → Taxable Temp. Difference → DTL'],
    ['SR','PARTICULARS','CARRYING AMT (₹)','TAX BASE (₹)','TEMP DIFF (₹)','NATURE','TAX EFFECT (₹)','NOTES']);

    let lTotalDTA=0, lTotalDTL=0;
    dt.liabRows.forEach((r,i)=>{
      rows.push([i+1,r.label,fmt(r.ca),fmt(r.tb),fmt(r.diff),r.nature,fmt(r.te),r.note||'']);
      if(r.nature==='DTA') lTotalDTA+=r.te; else if(r.nature==='DTL') lTotalDTL+=r.te;
    });
    rows.push(['','SUBTOTAL — LIABILITIES','','','','DTA',fmt(lTotalDTA),'']);
    rows.push(['','','','','','DTL',fmt(lTotalDTL),'']);

    rows.push([''],
    ['SECTION C — OTHER DEFERRED ITEMS (Losses / MAT Credit)'],
    ['SR','PARTICULARS','BASE AMOUNT (₹)','','','TYPE','TAX EFFECT (₹)','NOTES']);
    let oTotalDTA=0, oTotalDTL=0;
    dt.otherRows.forEach((r,i)=>{
      rows.push([i+1,r.label,fmt(r.amt),'','',r.type.toUpperCase(),fmt(r.te),r.note||'']);
      if(r.type==='dta') oTotalDTA+=r.te; else oTotalDTL+=r.te;
    });

    rows.push([''],
    ['CONSOLIDATED DEFERRED TAX POSITION'],
    ['','Gross Deferred Tax Asset (DTA)','','',' ',fmt(dt.grossDTA),'',''],
    ['','Gross Deferred Tax Liability (DTL)','','',' ',fmt(dt.grossDTL),'',''],
    ['','Net DTA / (DTL)','','','',fmt(dt.grossDTA-dt.grossDTL),'',''],
    ['','Deferred Tax P&L Impact (Charge) / Credit','','','',fmt(dt.dtPLCharge),'','']);

    const WS = XLSX.utils.aoa_to_sheet(rows);
    WS['!cols']=[{wch:6},{wch:52},{wch:18},{wch:18},{wch:16},{wch:8},{wch:16},{wch:40}];
    XLSX.utils.book_append_sheet(WB, WS, 'DT');
  }

  /* ══════════════════════════════════════
     SHEET 4 — MOVEMENT
  ══════════════════════════════════════ */
  function addMovementSheet(WB, dt){
    const matNew=v('mv-mat-new'), matUtil=v('ct-matutil');
    const rows=[
      [FIRM],
      ['DTA / DTL MOVEMENT SCHEDULE'],
      ['Client: '+s('ci-name')+'  |  FY: '+s('ci-fy')],
      [''],
      ['DEFERRED TAX ASSET — MOVEMENT','','₹'],
      ['Opening DTA (per prior year audited FS)','',fmt(v('ob-dta'))],
      ['Add: DTA recognised during the year','',fmt(dt.grossDTA)],
      ['Less: DTA reversed / utilised','','—'],
      ['Add: MAT Credit Entitlement recognised','',fmt(matNew)],
      ['Less: MAT Credit utilised','',fmt(matUtil)],
      ['CLOSING DTA (to Balance Sheet — Non Current)','',fmt(dt.closingDTA)],
      [''],
      ['DEFERRED TAX LIABILITY — MOVEMENT','','₹'],
      ['Opening DTL (per prior year audited FS)','',fmt(v('ob-dtl'))],
      ['Add: DTL created during the year','',fmt(dt.grossDTL)],
      ['Less: DTL reversed during the year','','—'],
      ['CLOSING DTL (to Balance Sheet — Non Current)','',fmt(dt.closingDTL)],
      [''],
      ['MAT CREDIT ENTITLEMENT — MOVEMENT (Sec 115JAA)','','₹'],
      ['Opening MAT Credit (per prior year)','',fmt(v('ob-mat'))],
      ['Add: MAT Credit recognised this year','',fmt(matNew)],
      ['Less: MAT Credit utilised during the year','',fmt(matUtil)],
      ['CLOSING MAT CREDIT (to Balance Sheet)','',fmt(dt.closingMAT)],
      [''],
      ['NET P&L IMPACT — DEFERRED TAX','','₹'],
      ['Deferred Tax (Charge) / Credit for the year','',fmt(dt.dtPLCharge)],
    ];
    const WS=XLSX.utils.aoa_to_sheet(rows);
    WS['!cols']=[{wch:52},{wch:6},{wch:20}];
    XLSX.utils.book_append_sheet(WB, WS, 'MOV');
  }

  /* ══════════════════════════════════════
     SHEET 5 — JOURNAL ENTRIES
  ══════════════════════════════════════ */
  function addJESheet(WB, ct, dt){
    const fy=s('ci-fy'), dt_=s('ci-date'), rate=v('ci-rate');
    const matNew=v('mv-mat-new');
    const rows=[
      [FIRM],
      ['JOURNAL ENTRIES — Income Tax Provision | '+fy],
      ['Client: '+s('ci-name')],
      [''],
      ['JOURNAL ENTRY 1 — CURRENT TAX PROVISION'],
      ['Date','Account','Dr (₹)','Cr (₹)','Narration'],
      [dt_,'Income Tax Expense — Current',fmt(ct.grossTax),'','Being current tax provision @ '+rate.toFixed(3)+'%'],
      [dt_,'Advance Tax / TDS Receivable','',fmt(ct.tds),'Adjusted against current tax payable'],
      [dt_,'MAT Credit Utilised','',fmt(ct.matUtil),'MAT credit set off u/s 115JAA'],
      [dt_,'Provision for Current Tax','',fmt(ct.netCT),'Net payable — current year'],
      ['','TOTAL',fmt(ct.grossTax),fmt(ct.grossTax),'Dr = Cr ✓'],
      [''],
      ['JOURNAL ENTRY 2 — DEFERRED TAX (Ind AS 12 — Balance Sheet Approach)'],
      ['Date','Account','Dr (₹)','Cr (₹)','Narration'],
    ];

    const isDTAcredit = dt.dtPLCharge < 0;
    if(isDTAcredit){
      rows.push([dt_,'Deferred Tax Asset',fmt(Math.abs(dt.dtPLCharge)),'','DTA recognised — deductible temporary differences']);
      rows.push([dt_,'Deferred Tax Income (P&L)','',fmt(Math.abs(dt.dtPLCharge)),'Credit to P&L — Ind AS 12']);
    } else {
      rows.push([dt_,'Deferred Tax Expense (P&L)',fmt(dt.dtPLCharge),'','Charge to P&L — Ind AS 12']);
      rows.push([dt_,'Deferred Tax Liability','',fmt(dt.dtPLCharge),'DTL created — taxable temporary differences']);
    }
    rows.push(['','TOTAL',fmt(Math.abs(dt.dtPLCharge)),fmt(Math.abs(dt.dtPLCharge)),'Dr = Cr ✓']);

    if(matNew>0){
      rows.push(['']);
      rows.push(['JOURNAL ENTRY 3 — MAT CREDIT ENTITLEMENT (Sec 115JAA)']);
      rows.push(['Date','Account','Dr (₹)','Cr (₹)','Narration']);
      rows.push([dt_,'MAT Credit Entitlement — DTA',fmt(matNew),'','MAT credit entitled u/s 115JAA']);
      rows.push([dt_,'MAT Credit Income (P&L)','',fmt(matNew),'Credit to P&L — reasonable certainty of utilisation']);
      rows.push(['','TOTAL',fmt(matNew),fmt(matNew),'Dr = Cr ✓']);
    }

    const WS=XLSX.utils.aoa_to_sheet(rows);
    WS['!cols']=[{wch:14},{wch:48},{wch:16},{wch:16},{wch:52}];
    XLSX.utils.book_append_sheet(WB, WS, 'JE');
  }

  /* ══════════════════════════════════════
     SHEET 6 — DISCLOSURE NOTE
  ══════════════════════════════════════ */
  function addDisclosureSheet(WB, ct, dt, total, etr){
    const rate=v('ci-rate');
    const rows=[
      [FIRM],
      ['IND AS 12 — DISCLOSURE NOTE'],
      ['Client: '+s('ci-name')+'  |  FY: '+s('ci-fy')],
      [''],
      ['Note ___ : Income Taxes'],
      [''],
      ['(a) Amount recognised in Statement of Profit and Loss','',''],
      ['Particulars','CY (₹)','PY (₹)'],
      ['Current tax on profits',fmt(ct.grossTax),'—'],
      ['Adjustments in respect of earlier years','—','—'],
      ['Total current tax',fmt(ct.grossTax),'—'],
      ['Origination and reversal of temporary differences',fmt(dt.dtPLCharge),'—'],
      ['Effect of change in tax rate','—','—'],
      ['Total deferred tax expense / (credit)',fmt(dt.dtPLCharge),'—'],
      ['Income tax expense for the year',fmt(total),'—'],
      [''],
      ['(b) Effective Tax Rate Reconciliation','',''],
      ['Particulars','Amount (₹)','Rate (%)'],
      ['Profit Before Tax',fmt(ct.bookProfit),'100.00%'],
      ['Tax at statutory rate of '+rate.toFixed(3)+'%',fmt(ct.bookProfit*rate/100),rate.toFixed(3)+'%'],
      ['Non-deductible expenses','—','—'],
      ['Exempt income','—','—'],
      ['Effect of deferred tax movement',fmt(dt.dtPLCharge),ct.bookProfit?(dt.dtPLCharge/ct.bookProfit*100).toFixed(2)+'%':'—'],
      ['Total income tax expense',fmt(total),etr.toFixed(2)+'%'],
      [''],
      ['(c) Deferred Tax Balance Sheet Position','',''],
      ['Particulars','DTA (₹)','DTL (₹)'],
      ['Gross Deferred Tax',fmt(dt.grossDTA),fmt(dt.grossDTL)],
      ['Net Position (DTA - DTL)',fmt(dt.grossDTA-dt.grossDTL),''],
      ['Opening Balances',fmt(v('ob-dta')),fmt(v('ob-dtl'))],
      ['Closing Balances',fmt(dt.closingDTA),fmt(dt.closingDTL)],
      [''],
      ['Tax rate used for measurement: '+rate.toFixed(3)+'% (enacted rate as at balance sheet date)'],
      ['Basis: Ind AS 12 — Income Taxes, Companies (Indian Accounting Standards) Rules, 2015'],
    ];
    const WS=XLSX.utils.aoa_to_sheet(rows);
    WS['!cols']=[{wch:58},{wch:18},{wch:16}];
    XLSX.utils.book_append_sheet(WB, WS, 'DISC');
  }

  /* ══════════════════════════════════════
     SHEET 7 — ETR
  ══════════════════════════════════════ */
  function addETRSheet(WB, ct, dt, total, etr){
    const rate=v('ci-rate');
    const rows=[
      [FIRM],
      ['EFFECTIVE TAX RATE RECONCILIATION — Ind AS 12.81(c)'],
      ['Client: '+s('ci-name')+'  |  FY: '+s('ci-fy')],
      [''],
      ['Particulars','₹','Rate %'],
      ['Profit Before Tax (Book Profit)',fmt(ct.bookProfit),'—'],
      ['Tax at statutory income tax rate of '+rate.toFixed(3)+'%',fmt(ct.bookProfit*rate/100),rate.toFixed(3)+'%'],
      ['Non-deductible expenses (penalties, personal exp etc.)','—','—'],
      ['Effect of exempt income (dividend, LTCG etc.)','—','—'],
      ['Effect of deferred tax movement',fmt(dt.dtPLCharge),ct.bookProfit?(dt.dtPLCharge/ct.bookProfit*100).toFixed(3)+'%':'—'],
      ['Effect of deductions (80IC, 80JJAA, 80G etc.)','—','—'],
      ['Other adjustments','—','—'],
      ['Effective tax rate / Total income tax expense',fmt(total),etr.toFixed(2)+'%'],
      [''],
      ['STATUTORY RATE',rate.toFixed(3)+'%'],
      ['EFFECTIVE RATE',etr.toFixed(2)+'%'],
      ['VARIANCE (ETR - Statutory)',(etr-rate).toFixed(2)+'%'],
    ];
    const WS=XLSX.utils.aoa_to_sheet(rows);
    WS['!cols']=[{wch:58},{wch:20},{wch:16}];
    XLSX.utils.book_append_sheet(WB, WS, 'ETR');
  }

  /* ══════════════════════════════════════
     SHEET 8 — CHECKLIST
  ══════════════════════════════════════ */
  function addChecklistSheet(WB){
    const checks=[
      ['Balance sheet approach applied per Ind AS 12','Ind AS 12.15','Done'],
      ['Current tax computed on taxable income per IT Act','Sec 115BAA/JB','Done'],
      ['Temporary differences identified for all BS items','Ind AS 12.5','Done'],
      ['Tax base correctly determined per IT Act','Ind AS 12.7','Done'],
      ['Deferred tax rate = enacted rate at BS date','Ind AS 12.47','Done'],
      ['DTA recognised only where future profits probable','Ind AS 12.24','Done'],
      ['Virtual certainty test applied for losses','Ind AS 12.29','Review'],
      ['Initial recognition exception applied','Ind AS 12.15(b)','Done'],
      ['Deferred taxes NOT discounted','Ind AS 12.53','Done'],
      ['DTA/DTL offset only where enforceable right exists','Ind AS 12.74','Done'],
      ['Opening balances agreed to prior year FS','SA 520','Review'],
      ['MAT credit recognised separately as DTA','Sec 115JAA','Done'],
      ['DTA/DTL classified as Non-Current in BS','Ind AS 1.56','Done'],
      ['ETR reconciliation prepared and disclosed','Ind AS 12.81(c)','Done'],
      ['Disclosure per Ind AS 12.79-88 prepared','Ind AS 12.79','Done'],
      ['Journal entries balanced — Dr = Cr','SA 300','Done'],
      ['Compliance with Companies Act Sch III','Sch III','Done'],
    ];
    const rows=[
      [FIRM],
      ['AUDITOR\'S CHECKLIST — Deferred Tax Quality Control'],
      ['Client: '+s('ci-name')+'  |  FY: '+s('ci-fy')+'  |  Date: '+new Date().toLocaleDateString('en-IN')],
      [''],
      ['SR','CHECK POINT','REFERENCE','STATUS','REMARKS'],
      ...checks.map((c,i)=>[i+1,...c,'']),
      [''],
      ['Prepared By: '+s('ci-prep'),'','','Reviewed By: '+s('ci-rev'),''],
      ['Date: '+s('ci-prepdate'),'','','',''],
    ];
    const WS=XLSX.utils.aoa_to_sheet(rows);
      WS['!cols']=[{wch:6},{wch:60},{wch:18},{wch:10},{wch:30}];
    XLSX.utils.book_append_sheet(WB, WS, 'CHK');
  }

  /* ── script loader ── */
  function loadScript(src){
    return new Promise((res,rej)=>{
      const s=document.createElement('script');
      s.src=src; s.onload=res; s.onerror=rej;
      document.head.appendChild(s);
    });
  }

  return { exportWorkpaper };
})();
