'use strict';

/**
 * EXPORT.JS — Getting the workpaper out.
 *
 * Excel uses SheetJS, fetched from a CDN the first time it is needed so the
 * app still loads instantly for anyone who never exports. Everything else is
 * generated with no dependency at all, so print, JSON and CSV keep working
 * with no network connection.
 */

const Exporter = (() => {

  const f = n => U.round(n, 0);
  const SHEETJS = 'https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';

  function loadScript(src) {
    return new Promise((resolve, reject) => {
      const s = document.createElement('script');
      s.src = src;
      s.async = true;
      s.onload = resolve;
      s.onerror = () => reject(new Error('Script failed to load'));
      document.head.appendChild(s);
    });
  }

  const safeName = (s, fallback) => (String(s || '').trim().replace(/[^\w\- ]+/g, '').replace(/\s+/g, '_') || fallback);

  /* ==========================================================
     EXCEL
     ========================================================== */

  async function toExcel(r) {
    if (!r) return;
    const t = U.toast('Building the workbook…', 'info', 20000);

    if (!window.XLSX) {
      try {
        await loadScript(SHEETJS);
      } catch {
        t.remove();
        U.toast('Could not load the spreadsheet library. Check the connection, or use Print to PDF instead.', 'err', 6000);
        return;
      }
    }

    const { eng, ct, dt, te, etr, jes } = r;
    const wb = XLSX.utils.book_new();
    wb.Props = {
      Title: `Tax provision — ${eng.name || 'Client'} ${eng.fy}`,
      Author: Store.firm().name,
      CreatedDate: new Date()
    };

    const add = (name, rows, widths) => {
      const ws = XLSX.utils.aoa_to_sheet(rows);
      if (widths) ws['!cols'] = widths.map(w => ({ wch: w }));
      XLSX.utils.book_append_sheet(wb, ws, name);
    };

    const firm = Store.firm();
    const rateStr = eng.rate.toFixed(3) + '%';

    /* 1 — Cover */
    add('1 Cover', [
      [firm.name], [firm.tagline], [],
      ['INCOME TAX PROVISION WORKPAPER'],
      ['Ind AS 12 — Income Taxes · balance sheet approach'], [],
      ['Client', eng.name || ''],
      ['CIN', eng.cin || ''],
      ['PAN', eng.pan || ''],
      ['Financial year', eng.fy || ''],
      ['Reporting date', eng.bsDate || ''],
      ['Applicable rate', rateStr],
      ['MAT rate', eng.matRate ? eng.matRate.toFixed(3) + '%' : 'Not applicable'],
      ['Presentation', dt.offset ? 'Offset (Ind AS 12.74)' : 'Gross'],
      [],
      ['SUMMARY', 'Amount (Rs)'],
      ['Profit before tax', f(ct.bookProfit)],
      ['Taxable income', f(ct.taxableIncome)],
      ['Current tax expense', f(te.current + te.matEffect)],
      ['Deferred tax expense / (credit)', f(te.deferred)],
      ['Total tax expense', f(te.total)],
      ['Effective tax rate', Number.isFinite(te.etr) ? te.etr.toFixed(2) + '%' : '—'],
      [],
      ['Deferred tax asset (balance sheet)', f(dt.bsDTA)],
      ['Deferred tax liability (balance sheet)', f(dt.bsDTL)],
      ['MAT credit entitlement', f(dt.matClosing)],
      [],
      ['SIGN-OFF'],
      ['Prepared by', eng.preparedBy || ''],
      ['Reviewed by', eng.reviewedBy || ''],
      ['Date of preparation', eng.prepDate || ''],
      ['Status', eng.status === 'signed' ? `Signed off by ${eng.signedBy || ''}` : eng.status],
      [],
      ['Generated', new Date().toLocaleString('en-IN')],
      ['Generated by', Auth.currentUser()?.name || '']
    ], [42, 26]);

    /* 2 — Current tax */
    add('2 Current tax', [
      ['CURRENT TAX COMPUTATION', '', '', ''],
      ['Ind AS 12 / Income Tax Act, 1961', '', '', ''],
      [],
      ['#', 'Type', 'Nature', 'Particulars', 'Amount (Rs)'],
      ...ct.lines.map((l, i) => [
        i + 1,
        l.type === 'book' ? 'Book' : l.type === 'add' ? 'Add' : 'Less',
        l.type === 'book' ? '' : (l.nature === 'perm' ? 'Permanent' : 'Temporary'),
        l.label,
        f(l.effect)
      ]),
      [],
      ['', '', '', 'Taxable income / (loss)', f(ct.taxableIncome)],
      ['', '', '', 'Rate applied', rateStr],
      ['', '', '', 'Tax under normal provisions', f(ct.normalTax)],
      ...(ct.matRate ? [
        ['', '', '', 'Book profit u/s 115JB', f(ct.matBase)],
        ['', '', '', `MAT at ${ct.matRate.toFixed(3)}%`, f(ct.matTax)],
        ['', '', '', 'MAT applies?', ct.matApplies ? 'Yes' : 'No'],
        ['', '', '', 'MAT credit arising', f(ct.matCreditCreated)]
      ] : []),
      ['', '', '', 'Tax for the year', f(ct.taxForYear)],
      ['', '', '', 'Tax of earlier years', f(ct.priorYearAdj)],
      ['', '', '', 'CURRENT TAX EXPENSE', f(ct.currentTaxExpense)],
      [],
      ['', '', '', 'Less: MAT credit utilised', f(ct.matUtilised)],
      ['', '', '', 'Less: advance tax and TDS', f(ct.advanceTax)],
      ['', '', '', ct.isRefund ? 'NET REFUNDABLE' : 'NET PAYABLE', f(Math.abs(ct.netPayable))]
    ], [5, 9, 12, 62, 18]);

    /* 3 — Deferred tax schedule */
    const dtHead = ['#', 'Particulars', 'Carrying amount', 'Tax base', 'Difference', 'Gives', 'Opening effect', 'Closing effect', 'Movement', 'Route', 'Recognised'];
    const bsBlock = (title, rows) => [
      [title],
      dtHead,
      ...rows.map((x, i) => [
        i + 1, x.label, f(x.ca), f(x.tb), f(x.td), x.nature,
        f(x.signedOpen), f(x.signedClose), f(x.movement),
        x.alloc === 'oci' ? 'OCI' : 'P&L', x.recognised ? 'Yes' : 'No'
      ]),
      []
    ];

    add('3 Deferred tax', [
      ['DEFERRED TAX SCHEDULE — Ind AS 12 balance sheet approach'],
      [`Measured at ${rateStr}. A positive closing effect is an asset; a negative one is a liability.`],
      [],
      ...bsBlock('A · ASSETS', dt.assets),
      ...bsBlock('B · LIABILITIES AND PROVISIONS', dt.liabs),
      ['C · LOSSES AND CREDITS'],
      ['#', 'Particulars', 'Amount', 'Side', 'Already a tax amount', 'Opening effect', 'Closing effect', 'Movement', 'Route', 'Recognised', 'Expiry'],
      ...dt.others.map((x, i) => [
        i + 1, x.label, f(x.amt), x.side.toUpperCase(), x.isTaxAmount ? 'Yes' : 'No',
        f(x.signedOpen), f(x.signedClose), f(x.movement),
        x.alloc === 'oci' ? 'OCI' : 'P&L', x.recognised ? 'Yes' : 'No', x.expiry || ''
      ]),
      [],
      ['CONSOLIDATED', 'DTA', 'DTL'],
      ['A · Assets', f(dt.secA.dta), f(dt.secA.dtl)],
      ['B · Liabilities', f(dt.secL.dta), f(dt.secL.dtl)],
      ['C · Losses and credits', f(dt.secO.dta), f(dt.secO.dtl)],
      ['Gross deferred tax', f(dt.grossDTA), f(dt.grossDTL)],
      [dt.offset ? 'Net after offset' : 'Presented gross', f(dt.bsDTA), f(dt.bsDTL)],
      [],
      ['Deferred tax assets not recognised', f(dt.unrecognisedDTA)]
    ], [5, 58, 17, 17, 17, 8, 17, 17, 17, 8, 12]);

    /* 4 — Movement */
    add('4 Movement', [
      ['DEFERRED TAX MOVEMENT SCHEDULE'],
      [],
      ['Particulars', 'Opening', 'Through P&L', 'Through OCI', 'Closing'],
      ...dt.all
        .filter(x => Math.abs(x.signedOpen) > 0.5 || Math.abs(x.signedClose) > 0.5)
        .map(x => [x.label, f(x.signedOpen), x.alloc === 'pl' ? f(x.movement) : 0, x.alloc === 'oci' ? f(x.movement) : 0, f(x.signedClose)]),
      ['TOTAL', f(dt.openingRows), f(dt.movementPL), f(dt.movementOCI), f(dt.closingNet)],
      [],
      ['Opening per prior year financial statements', f(dt.openingFS)],
      ['Difference against the schedule', f(dt.openingDiff)],
      [],
      ['MAT CREDIT ENTITLEMENT — s.115JAA'],
      ['Opening', f(dt.matOpening)],
      ['Recognised in the year', f(dt.matCreated)],
      ['Utilised in the year', f(dt.matUtilised)],
      ['Closing', f(dt.matClosing)]
    ], [58, 18, 18, 18, 18]);

    /* 5 — Journals */
    const jeRows = [['JOURNAL ENTRIES'], []];
    jes.forEach(j => {
      jeRows.push([j.ref, j.title, j.standard, j.date]);
      jeRows.push(['', 'Account', 'Debit', 'Credit']);
      j.lines.forEach(l => jeRows.push(['', (l.side === 'Cr' ? '    ' : '') + l.side + ' ' + l.account, l.side === 'Dr' ? f(l.amount) : '', l.side === 'Cr' ? f(l.amount) : '']));
      jeRows.push(['', j.balanced ? 'Cast and cross-cast' : 'DOES NOT CAST', f(j.dr), f(j.cr)]);
      jeRows.push(['', '(' + j.narration + ')']);
      jeRows.push([]);
    });
    add('5 Journals', jeRows, [8, 62, 18, 18]);

    /* 6 — Effective rate */
    add('6 Effective rate', [
      ['RECONCILIATION OF THE EFFECTIVE TAX RATE — Ind AS 12.81(c)'],
      [],
      ['Particulars', 'Amount (Rs)', 'Rate (%)'],
      ['Profit before tax', f(ct.bookProfit), ''],
      ...etr.rows.map(x => [x.label, f(x.amount), Number.isFinite(x.pct) ? Number(x.pct.toFixed(2)) : '']),
      ['Tax expense and effective rate', f(te.total), Number.isFinite(te.etr) ? Number(te.etr.toFixed(2)) : ''],
      [],
      ['Residual', f(etr.residual)],
      ['Tolerance (0.5% of profit before tax)', f(etr.tolerance)],
      ['Within tolerance?', etr.residualMaterial ? 'NO — investigate' : 'Yes']
    ], [62, 20, 14]);

    /* 7 — Disclosure note */
    const noteEl = document.createElement('div');
    noteEl.innerHTML = Render.disclosure(r);
    add('7 Disclosure', noteEl.innerText.split('\n').filter(l => l.trim()).map(l => [l]), [110]);

    /* 8 — Checklist */
    add('8 Checklist', [
      ['AUDIT CHECKLIST'],
      [],
      ['Group', 'Point', 'Reference', 'Status', 'Marked by', 'Marked at'],
      ...Store.checklistTemplate().map(item => {
        const m = eng.checklist?.[item.id] || {};
        return [item.group, item.text, item.ref,
          m.state === 'done' ? 'Done' : m.state === 'na' ? 'Not applicable' : m.state === 'query' ? 'QUERY' : 'Not marked',
          m.by || '', m.at ? new Date(m.at).toLocaleString('en-IN') : ''];
      })
    ], [16, 78, 20, 15, 22, 20]);

    /* 9 — Tallies */
    add('9 Tallies', [
      ['RECONCILIATION CHECKS'],
      [],
      ['Check', 'Result', 'Detail'],
      ...r.tallies.items.map(x => [x.label, x.state === 'ok' ? 'Tallied' : x.state === 'query' ? 'QUERY' : 'Not applicable', x.detail]),
      [],
      ['OPEN POINTS'],
      ['Level', 'Point'],
      ...r.validation.items.map(x => [x.level === 'error' ? 'ERROR' : 'Check', x.msg])
    ], [46, 16, 78]);

    const file = `TaxProvision_${safeName(eng.name, 'Client')}_${safeName(eng.fy, 'FY')}.xlsx`;
    XLSX.writeFile(wb, file);
    t.remove();
    Store.log('Exported to Excel', eng.name || 'Untitled', eng.id);
    U.toast('Workbook downloaded', 'ok');
  }

  /* ==========================================================
     PRINT / PDF
     ========================================================== */

  function printWorkpaper(r, opts = {}) {
    if (!r) { U.toast('Open an engagement first.', 'err'); return; }
    const { eng, ct, dt, te, etr, jes } = r;
    const firm = Store.firm();
    const root = U.byId('print-root');

    const money = U.fmtBr;
    const noteOnly = opts.only === 'note';

    const head = `
      <div class="p-head">
        <div>
          <div class="p-firm">${U.esc(firm.name)}</div>
          <div class="p-tag">${U.esc(firm.tagline)}</div>
        </div>
        <div class="p-ref">
          <div>WP · Income taxes</div>
          <div>${U.esc(eng.fy || '')}</div>
        </div>
      </div>
      <div class="p-title">
        <h1>${U.esc(eng.name || 'Client')}</h1>
        <p>Income tax provision under Ind AS 12 · year ended ${U.esc(U.fmtDateLong(eng.bsDate))} · measured at ${eng.rate.toFixed(3)}%</p>
      </div>`;

    const signBlock = `
      <div class="p-sign">
        <div><span>Prepared by</span><b>${U.esc(eng.preparedBy || '—')}</b><i>${U.esc(U.fmtDate(eng.prepDate))}</i></div>
        <div><span>Reviewed by</span><b>${U.esc(eng.reviewedBy || '—')}</b><i>${eng.signedAt ? U.esc(U.fmtDate(eng.signedAt)) : '—'}</i></div>
        <div><span>Status</span><b>${eng.status === 'signed' ? 'Signed off' : eng.status === 'review' ? 'Under review' : 'Draft'}</b><i>${U.esc(eng.signedBy || '')}</i></div>
      </div>`;

    const tally = `
      <h2>Reconciliation checks</h2>
      <table class="p-tbl">
        <thead><tr><th>Check</th><th style="width:80px">Result</th><th style="width:210px">Detail</th></tr></thead>
        <tbody>${r.tallies.items.map(x => `<tr>
          <td>${U.esc(x.label)}</td>
          <td>${x.state === 'ok' ? '✓ Tallied' : x.state === 'query' ? 'Query' : '—'}</td>
          <td>${U.esc(x.detail)}</td></tr>`).join('')}
        </tbody>
      </table>`;

    const body = noteOnly ? `
      ${head}
      <h2>Draft note for the financial statements</h2>
      ${Render.disclosure(r)}
      ${signBlock}` : `
      ${head}

      <h2>1 · Summary</h2>
      <table class="p-tbl">
        <tbody>
          <tr><td>Profit before tax</td><td class="r">${money(ct.bookProfit)}</td></tr>
          <tr><td>Taxable income</td><td class="r">${money(ct.taxableIncome)}</td></tr>
          <tr><td>Current tax expense</td><td class="r">${money(te.current + te.matEffect)}</td></tr>
          <tr><td>Deferred tax expense / (credit)</td><td class="r">${money(te.deferred)}</td></tr>
          <tr class="p-tot"><td>Total tax expense</td><td class="r">${money(te.total)}</td></tr>
          <tr><td>Effective tax rate</td><td class="r">${U.fmtPct(te.etr)}</td></tr>
          <tr><td>Deferred tax asset / (liability) — net</td><td class="r">${money(dt.closingNet)}</td></tr>
          <tr><td>MAT credit entitlement</td><td class="r">${money(dt.matClosing)}</td></tr>
        </tbody>
      </table>

      <h2>2 · Current tax</h2>
      <table class="p-tbl">
        <thead><tr><th style="width:24px">#</th><th style="width:56px">Type</th><th>Particulars</th><th class="r" style="width:110px">Amount</th></tr></thead>
        <tbody>${ct.lines.map((l, i) => `<tr>
          <td>${i + 1}</td>
          <td>${l.type === 'book' ? 'Book' : l.type === 'add' ? 'Add' : 'Less'}${l.type !== 'book' ? ` <small>${l.nature === 'perm' ? 'P' : 'T'}</small>` : ''}</td>
          <td>${U.esc(l.label)}</td>
          <td class="r">${money(l.effect)}</td></tr>`).join('')}
          <tr class="p-sub"><td colspan="3">Taxable income</td><td class="r">${money(ct.taxableIncome)}</td></tr>
          <tr><td colspan="3">Tax under the normal provisions at ${ct.rate.toFixed(3)}%</td><td class="r">${money(ct.normalTax)}</td></tr>
          ${ct.matTax ? `<tr><td colspan="3">MAT at ${ct.matRate.toFixed(3)}% on book profit of ${U.fmt(ct.matBase)}</td><td class="r">${money(ct.matTax)}</td></tr>` : ''}
          <tr class="p-tot"><td colspan="3">Current tax expense</td><td class="r">${money(ct.currentTaxExpense)}</td></tr>
        </tbody>
      </table>

      <h2 class="p-break">3 · Deferred tax schedule</h2>
      <table class="p-tbl">
        <thead><tr>
          <th>Particulars</th><th class="r" style="width:88px">Carrying</th><th class="r" style="width:88px">Tax base</th>
          <th class="r" style="width:88px">Difference</th><th class="r" style="width:88px">Opening</th><th class="r" style="width:88px">Closing</th>
        </tr></thead>
        <tbody>
          ${[['A · Assets', dt.assets], ['B · Liabilities and provisions', dt.liabs]].map(([t, rows]) => `
            <tr class="p-grp"><td colspan="6">${t}</td></tr>
            ${rows.map(x => `<tr><td>${U.esc(x.label)}${x.recognised ? '' : ' <small>(not recognised)</small>'}${x.alloc === 'oci' ? ' <small>OCI</small>' : ''}</td>
              <td class="r">${money(x.ca)}</td><td class="r">${money(x.tb)}</td><td class="r">${money(x.td)}</td>
              <td class="r">${money(x.signedOpen)}</td><td class="r">${money(x.signedClose)}</td></tr>`).join('')}`).join('')}
          <tr class="p-grp"><td colspan="6">C · Losses and credits</td></tr>
          ${dt.others.map(x => `<tr><td>${U.esc(x.label)}${x.recognised ? '' : ' <small>(not recognised)</small>'}</td>
            <td class="r" colspan="3">${money(x.amt)}</td>
            <td class="r">${money(x.signedOpen)}</td><td class="r">${money(x.signedClose)}</td></tr>`).join('')}
          <tr class="p-tot"><td colspan="4">Net deferred tax asset / (liability)</td>
            <td class="r">${money(dt.openingRows)}</td><td class="r">${money(dt.closingNet)}</td></tr>
        </tbody>
      </table>

      <h2>4 · Movement</h2>
      <table class="p-tbl">
        <thead><tr><th>Particulars</th><th class="r" style="width:110px">Opening</th><th class="r" style="width:110px">P&amp;L</th><th class="r" style="width:110px">OCI</th><th class="r" style="width:110px">Closing</th></tr></thead>
        <tbody>
          <tr><td>Net deferred tax</td><td class="r">${money(dt.openingRows)}</td><td class="r">${money(dt.movementPL)}</td><td class="r">${money(dt.movementOCI)}</td><td class="r">${money(dt.closingNet)}</td></tr>
          <tr><td>MAT credit entitlement</td><td class="r">${money(dt.matOpening)}</td><td class="r">${money(dt.matCreated - dt.matUtilised)}</td><td class="r">—</td><td class="r">${money(dt.matClosing)}</td></tr>
        </tbody>
      </table>

      <h2 class="p-break">5 · Journal entries</h2>
      ${jes.map(j => `
        <div class="p-je">
          <div class="p-je-h"><b>${U.esc(j.ref)} · ${U.esc(j.title)}</b><span>${U.esc(j.standard)} · ${U.esc(j.date)}</span></div>
          <table class="p-tbl">
            <thead><tr><th style="width:28px"></th><th>Account</th><th class="r" style="width:110px">Debit</th><th class="r" style="width:110px">Credit</th></tr></thead>
            <tbody>
              ${j.lines.map(l => `<tr><td>${l.side}</td><td${l.side === 'Cr' ? ' style="padding-left:22px"' : ''}>${U.esc(l.account)}</td>
                <td class="r">${l.side === 'Dr' ? U.fmt(l.amount) : ''}</td><td class="r">${l.side === 'Cr' ? U.fmt(l.amount) : ''}</td></tr>`).join('')}
              <tr class="p-sub"><td></td><td>${j.balanced ? 'Cast and cross-cast ✓' : 'Does not cast'}</td>
                <td class="r">${U.fmt(j.dr)}</td><td class="r">${U.fmt(j.cr)}</td></tr>
            </tbody>
          </table>
          <p class="p-narr">(${U.esc(j.narration)})</p>
        </div>`).join('')}

      <h2 class="p-break">6 · Effective rate reconciliation</h2>
      <table class="p-tbl">
        <thead><tr><th>Particulars</th><th class="r" style="width:120px">Amount</th><th class="r" style="width:90px">Rate</th></tr></thead>
        <tbody>
          <tr><td>Profit before tax</td><td class="r">${money(ct.bookProfit)}</td><td class="r">—</td></tr>
          ${etr.rows.map(x => `<tr${x.indent ? ' class="p-in"' : ''}><td>${U.esc(x.label)}</td><td class="r">${money(x.amount)}</td>
            <td class="r">${Number.isFinite(x.pct) ? x.pct.toFixed(2) + '%' : '—'}</td></tr>`).join('')}
          <tr class="p-tot"><td>Tax expense and effective rate</td><td class="r">${money(te.total)}</td><td class="r">${U.fmtPct(te.etr)}</td></tr>
        </tbody>
      </table>

      <h2 class="p-break">7 · Draft note for the financial statements</h2>
      ${Render.disclosure(r)}

      <h2 class="p-break">8 · Checklist</h2>
      <table class="p-tbl">
        <thead><tr><th>Point</th><th style="width:110px">Reference</th><th style="width:80px">Status</th><th style="width:130px">Marked by</th></tr></thead>
        <tbody>${Store.checklistTemplate().map(item => {
          const m = eng.checklist?.[item.id] || {};
          return `<tr><td>${U.esc(item.text)}</td><td>${U.esc(item.ref)}</td>
            <td>${m.state === 'done' ? '✓ Done' : m.state === 'na' ? 'N/A' : m.state === 'query' ? 'Query' : '—'}</td>
            <td>${U.esc(m.by || '')}</td></tr>`;
        }).join('')}</tbody>
      </table>

      ${tally}
      ${signBlock}
      <p class="p-foot">Prepared with the ${U.esc(firm.name)} Ind AS 12 workpaper tool on ${new Date().toLocaleString('en-IN')} by ${U.esc(Auth.currentUser()?.name || '')}. This workpaper supports, and does not replace, the professional judgement of the engagement team.</p>`;

    root.innerHTML = body;
    const restore = document.title;
    document.title = `${safeName(eng.name, 'Client')}_${safeName(eng.fy, 'FY')}_TaxProvision`;

    let done = false;
    const cleanup = () => {
      if (done) return;
      done = true;
      document.title = restore;
      root.innerHTML = '';
      window.removeEventListener('afterprint', cleanup);
      mq?.removeEventListener?.('change', onMq);
    };

    // `afterprint` is the reliable signal. Firefox and some Safari builds fire
    // it late or not at all, so a print media-query listener backs it up.
    window.addEventListener('afterprint', cleanup);
    const mq = window.matchMedia?.('print');
    const onMq = ev => { if (!ev.matches) cleanup(); };
    mq?.addEventListener?.('change', onMq);

    // A long stop only, in case neither signal arrives. The old one-and-a-half
    // second timer would blank the sheet while the dialog was still open.
    setTimeout(cleanup, 120000);

    // Give the browser a frame to lay the sheet out before opening the dialog.
    requestAnimationFrame(() => requestAnimationFrame(() => window.print()));

    Store.log('Printed workpaper', eng.name || 'Untitled', eng.id);
  }

  /* ==========================================================
     JSON / CSV
     ========================================================== */

  function toJson(eng) {
    const payload = {
      kind: 'kgs.indas12.engagement',
      version: 1,
      exportedAt: new Date().toISOString(),
      exportedBy: Auth.currentUser()?.name || '',
      engagement: eng
    };
    U.download(`TaxProvision_${safeName(eng.name, 'Client')}_${safeName(eng.fy, 'FY')}.json`, JSON.stringify(payload, null, 2));
    Store.log('Exported engagement as JSON', eng.name || 'Untitled', eng.id);
    U.toast('Backup downloaded', 'ok');
  }

  function importEngagement(onDone) {
    const inp = document.createElement('input');
    inp.type = 'file';
    inp.accept = 'application/json,.json';
    inp.addEventListener('change', async () => {
      const file = inp.files?.[0];
      if (!file) return;
      try {
        const parsed = JSON.parse(await file.text());
        const eng = parsed.engagement || (parsed.id && parsed.ct ? parsed : null);
        if (!eng || !eng.ct || !eng.dt) throw new Error('shape');
        eng.id = U.uid('eng');
        eng.ownerId = Auth.currentUser()?.id || null;
        eng.assignedTo = eng.ownerId;
        eng.status = 'draft';
        eng.locked = false;
        eng.createdAt = eng.updatedAt = new Date().toISOString();
        eng.name = (eng.name || 'Imported engagement');
        Store.addEngagement(eng);
        Store.log('Imported engagement', eng.name, eng.id);
        U.toast(`Imported ${eng.name}`, 'ok');
        onDone?.(eng);
      } catch {
        U.toast('That file is not an engagement export.', 'err', 5000);
      }
    });
    inp.click();
  }

  function toCsv(r) {
    const cell = v => {
      const s = String(v ?? '');
      return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
    };
    const rows = [
      ['Section', 'Particulars', 'Carrying amount', 'Tax base', 'Difference', 'Gives', 'Opening effect', 'Closing effect', 'Movement', 'Route', 'Recognised'],
      ...r.dt.assets.map(x => ['Assets', x.label, f(x.ca), f(x.tb), f(x.td), x.nature, f(x.signedOpen), f(x.signedClose), f(x.movement), x.alloc, x.recognised ? 'Yes' : 'No']),
      ...r.dt.liabs.map(x => ['Liabilities', x.label, f(x.ca), f(x.tb), f(x.td), x.nature, f(x.signedOpen), f(x.signedClose), f(x.movement), x.alloc, x.recognised ? 'Yes' : 'No']),
      ...r.dt.others.map(x => ['Losses and credits', x.label, f(x.amt), '', '', x.nature, f(x.signedOpen), f(x.signedClose), f(x.movement), x.alloc, x.recognised ? 'Yes' : 'No'])
    ];
    // A leading BOM makes Excel open this as UTF-8 rather than mangling it.
    U.download(
      `DeferredTax_${safeName(r.eng.name, 'Client')}_${safeName(r.eng.fy, 'FY')}.csv`,
      '\ufeff' + rows.map(row => row.map(cell).join(',')).join('\r\n'),
      'text/csv;charset=utf-8'
    );
    U.toast('Schedule downloaded', 'ok');
  }

  return { toExcel, printWorkpaper, toJson, toCsv, importEngagement, loadScript, safeName };
})();
